name: Ouest
options:
  bundleIdPrefix: com.ouest
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  Ouest:
    type: application
    platform: iOS
    sources:
      - Ouest
    settings:
      base:
        INFOPLIST_FILE: Ouest/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_BUNDLE_IDENTIFIER: com.ouest.app
        INFOPLIST_KEY_CFBundleDisplayName: Ouest
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)
      configs:
        Debug:
          xcconfig: Ouest/Configuration/Debug.xcconfig
        Release:
          xcconfig: Ouest/Configuration/Release.xcconfig
    dependencies:
      - package: Supabase
    info:
      path: Ouest/Resources/Info.plist
      properties:
        CFBundleDisplayName: Ouest
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)

  OuestTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - OuestTests
    dependencies:
      - target: Ouest

  OuestUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - OuestUITests
    dependencies:
      - target: Ouest
