import Foundation

/// Provides country data (ISO 3166-1 alpha-3 codes, names, flag emojis).
enum CountryHelper {

    struct Country: Identifiable, Sendable {
        let code: String   // ISO 3166-1 alpha-3 (e.g. "USA")
        let alpha2: String // ISO 3166-1 alpha-2 (e.g. "US")
        let name: String

        var id: String { code }

        /// Flag emoji derived from the 2-letter code
        var flag: String {
            let base: UInt32 = 127_397
            return alpha2.unicodeScalars.compactMap {
                UnicodeScalar(base + $0.value).map(String.init)
            }.joined()
        }
    }

    /// Finds a country by its 3-letter or 2-letter code
    static func country(for code: String) -> Country? {
        let upper = code.uppercased()
        return allCountries.first { $0.code == upper || $0.alpha2 == upper }
    }

    /// Display string: "🇺🇸 United States"
    static func displayName(for code: String) -> String? {
        guard let c = country(for: code) else { return nil }
        return "\(c.flag) \(c.name)"
    }

    /// Flag emoji for a code
    static func flag(for code: String) -> String {
        country(for: code)?.flag ?? "🏳️"
    }

    // MARK: - All Countries (sorted by name)

    static let allCountries: [Country] = [
        Country(code: "AFG", alpha2: "AF", name: "Afghanistan"),
        Country(code: "ALB", alpha2: "AL", name: "Albania"),
        Country(code: "DZA", alpha2: "DZ", name: "Algeria"),
        Country(code: "AND", alpha2: "AD", name: "Andorra"),
        Country(code: "AGO", alpha2: "AO", name: "Angola"),
        Country(code: "ATG", alpha2: "AG", name: "Antigua and Barbuda"),
        Country(code: "ARG", alpha2: "AR", name: "Argentina"),
        Country(code: "ARM", alpha2: "AM", name: "Armenia"),
        Country(code: "AUS", alpha2: "AU", name: "Australia"),
        Country(code: "AUT", alpha2: "AT", name: "Austria"),
        Country(code: "AZE", alpha2: "AZ", name: "Azerbaijan"),
        Country(code: "BHS", alpha2: "BS", name: "Bahamas"),
        Country(code: "BHR", alpha2: "BH", name: "Bahrain"),
        Country(code: "BGD", alpha2: "BD", name: "Bangladesh"),
        Country(code: "BRB", alpha2: "BB", name: "Barbados"),
        Country(code: "BLR", alpha2: "BY", name: "Belarus"),
        Country(code: "BEL", alpha2: "BE", name: "Belgium"),
        Country(code: "BLZ", alpha2: "BZ", name: "Belize"),
        Country(code: "BEN", alpha2: "BJ", name: "Benin"),
        Country(code: "BTN", alpha2: "BT", name: "Bhutan"),
        Country(code: "BOL", alpha2: "BO", name: "Bolivia"),
        Country(code: "BIH", alpha2: "BA", name: "Bosnia and Herzegovina"),
        Country(code: "BWA", alpha2: "BW", name: "Botswana"),
        Country(code: "BRA", alpha2: "BR", name: "Brazil"),
        Country(code: "BRN", alpha2: "BN", name: "Brunei"),
        Country(code: "BGR", alpha2: "BG", name: "Bulgaria"),
        Country(code: "BFA", alpha2: "BF", name: "Burkina Faso"),
        Country(code: "BDI", alpha2: "BI", name: "Burundi"),
        Country(code: "CPV", alpha2: "CV", name: "Cabo Verde"),
        Country(code: "KHM", alpha2: "KH", name: "Cambodia"),
        Country(code: "CMR", alpha2: "CM", name: "Cameroon"),
        Country(code: "CAN", alpha2: "CA", name: "Canada"),
        Country(code: "CAF", alpha2: "CF", name: "Central African Republic"),
        Country(code: "TCD", alpha2: "TD", name: "Chad"),
        Country(code: "CHL", alpha2: "CL", name: "Chile"),
        Country(code: "CHN", alpha2: "CN", name: "China"),
        Country(code: "COL", alpha2: "CO", name: "Colombia"),
        Country(code: "COM", alpha2: "KM", name: "Comoros"),
        Country(code: "COG", alpha2: "CG", name: "Congo"),
        Country(code: "COD", alpha2: "CD", name: "Congo (DRC)"),
        Country(code: "CRI", alpha2: "CR", name: "Costa Rica"),
        Country(code: "CIV", alpha2: "CI", name: "Côte d'Ivoire"),
        Country(code: "HRV", alpha2: "HR", name: "Croatia"),
        Country(code: "CUB", alpha2: "CU", name: "Cuba"),
        Country(code: "CYP", alpha2: "CY", name: "Cyprus"),
        Country(code: "CZE", alpha2: "CZ", name: "Czechia"),
        Country(code: "DNK", alpha2: "DK", name: "Denmark"),
        Country(code: "DJI", alpha2: "DJ", name: "Djibouti"),
        Country(code: "DMA", alpha2: "DM", name: "Dominica"),
        Country(code: "DOM", alpha2: "DO", name: "Dominican Republic"),
        Country(code: "ECU", alpha2: "EC", name: "Ecuador"),
        Country(code: "EGY", alpha2: "EG", name: "Egypt"),
        Country(code: "SLV", alpha2: "SV", name: "El Salvador"),
        Country(code: "GNQ", alpha2: "GQ", name: "Equatorial Guinea"),
        Country(code: "ERI", alpha2: "ER", name: "Eritrea"),
        Country(code: "EST", alpha2: "EE", name: "Estonia"),
        Country(code: "SWZ", alpha2: "SZ", name: "Eswatini"),
        Country(code: "ETH", alpha2: "ET", name: "Ethiopia"),
        Country(code: "FJI", alpha2: "FJ", name: "Fiji"),
        Country(code: "FIN", alpha2: "FI", name: "Finland"),
        Country(code: "FRA", alpha2: "FR", name: "France"),
        Country(code: "GAB", alpha2: "GA", name: "Gabon"),
        Country(code: "GMB", alpha2: "GM", name: "Gambia"),
        Country(code: "GEO", alpha2: "GE", name: "Georgia"),
        Country(code: "DEU", alpha2: "DE", name: "Germany"),
        Country(code: "GHA", alpha2: "GH", name: "Ghana"),
        Country(code: "GRC", alpha2: "GR", name: "Greece"),
        Country(code: "GRD", alpha2: "GD", name: "Grenada"),
        Country(code: "GTM", alpha2: "GT", name: "Guatemala"),
        Country(code: "GIN", alpha2: "GN", name: "Guinea"),
        Country(code: "GNB", alpha2: "GW", name: "Guinea-Bissau"),
        Country(code: "GUY", alpha2: "GY", name: "Guyana"),
        Country(code: "HTI", alpha2: "HT", name: "Haiti"),
        Country(code: "HND", alpha2: "HN", name: "Honduras"),
        Country(code: "HUN", alpha2: "HU", name: "Hungary"),
        Country(code: "ISL", alpha2: "IS", name: "Iceland"),
        Country(code: "IND", alpha2: "IN", name: "India"),
        Country(code: "IDN", alpha2: "ID", name: "Indonesia"),
        Country(code: "IRN", alpha2: "IR", name: "Iran"),
        Country(code: "IRQ", alpha2: "IQ", name: "Iraq"),
        Country(code: "IRL", alpha2: "IE", name: "Ireland"),
        Country(code: "ISR", alpha2: "IL", name: "Israel"),
        Country(code: "ITA", alpha2: "IT", name: "Italy"),
        Country(code: "JAM", alpha2: "JM", name: "Jamaica"),
        Country(code: "JPN", alpha2: "JP", name: "Japan"),
        Country(code: "JOR", alpha2: "JO", name: "Jordan"),
        Country(code: "KAZ", alpha2: "KZ", name: "Kazakhstan"),
        Country(code: "KEN", alpha2: "KE", name: "Kenya"),
        Country(code: "KIR", alpha2: "KI", name: "Kiribati"),
        Country(code: "PRK", alpha2: "KP", name: "Korea (North)"),
        Country(code: "KOR", alpha2: "KR", name: "Korea (South)"),
        Country(code: "KWT", alpha2: "KW", name: "Kuwait"),
        Country(code: "KGZ", alpha2: "KG", name: "Kyrgyzstan"),
        Country(code: "LAO", alpha2: "LA", name: "Laos"),
        Country(code: "LVA", alpha2: "LV", name: "Latvia"),
        Country(code: "LBN", alpha2: "LB", name: "Lebanon"),
        Country(code: "LSO", alpha2: "LS", name: "Lesotho"),
        Country(code: "LBR", alpha2: "LR", name: "Liberia"),
        Country(code: "LBY", alpha2: "LY", name: "Libya"),
        Country(code: "LIE", alpha2: "LI", name: "Liechtenstein"),
        Country(code: "LTU", alpha2: "LT", name: "Lithuania"),
        Country(code: "LUX", alpha2: "LU", name: "Luxembourg"),
        Country(code: "MDG", alpha2: "MG", name: "Madagascar"),
        Country(code: "MWI", alpha2: "MW", name: "Malawi"),
        Country(code: "MYS", alpha2: "MY", name: "Malaysia"),
        Country(code: "MDV", alpha2: "MV", name: "Maldives"),
        Country(code: "MLI", alpha2: "ML", name: "Mali"),
        Country(code: "MLT", alpha2: "MT", name: "Malta"),
        Country(code: "MHL", alpha2: "MH", name: "Marshall Islands"),
        Country(code: "MRT", alpha2: "MR", name: "Mauritania"),
        Country(code: "MUS", alpha2: "MU", name: "Mauritius"),
        Country(code: "MEX", alpha2: "MX", name: "Mexico"),
        Country(code: "FSM", alpha2: "FM", name: "Micronesia"),
        Country(code: "MDA", alpha2: "MD", name: "Moldova"),
        Country(code: "MCO", alpha2: "MC", name: "Monaco"),
        Country(code: "MNG", alpha2: "MN", name: "Mongolia"),
        Country(code: "MNE", alpha2: "ME", name: "Montenegro"),
        Country(code: "MAR", alpha2: "MA", name: "Morocco"),
        Country(code: "MOZ", alpha2: "MZ", name: "Mozambique"),
        Country(code: "MMR", alpha2: "MM", name: "Myanmar"),
        Country(code: "NAM", alpha2: "NA", name: "Namibia"),
        Country(code: "NRU", alpha2: "NR", name: "Nauru"),
        Country(code: "NPL", alpha2: "NP", name: "Nepal"),
        Country(code: "NLD", alpha2: "NL", name: "Netherlands"),
        Country(code: "NZL", alpha2: "NZ", name: "New Zealand"),
        Country(code: "NIC", alpha2: "NI", name: "Nicaragua"),
        Country(code: "NER", alpha2: "NE", name: "Niger"),
        Country(code: "NGA", alpha2: "NG", name: "Nigeria"),
        Country(code: "MKD", alpha2: "MK", name: "North Macedonia"),
        Country(code: "NOR", alpha2: "NO", name: "Norway"),
        Country(code: "OMN", alpha2: "OM", name: "Oman"),
        Country(code: "PAK", alpha2: "PK", name: "Pakistan"),
        Country(code: "PLW", alpha2: "PW", name: "Palau"),
        Country(code: "PSE", alpha2: "PS", name: "Palestine"),
        Country(code: "PAN", alpha2: "PA", name: "Panama"),
        Country(code: "PNG", alpha2: "PG", name: "Papua New Guinea"),
        Country(code: "PRY", alpha2: "PY", name: "Paraguay"),
        Country(code: "PER", alpha2: "PE", name: "Peru"),
        Country(code: "PHL", alpha2: "PH", name: "Philippines"),
        Country(code: "POL", alpha2: "PL", name: "Poland"),
        Country(code: "PRT", alpha2: "PT", name: "Portugal"),
        Country(code: "QAT", alpha2: "QA", name: "Qatar"),
        Country(code: "ROU", alpha2: "RO", name: "Romania"),
        Country(code: "RUS", alpha2: "RU", name: "Russia"),
        Country(code: "RWA", alpha2: "RW", name: "Rwanda"),
        Country(code: "KNA", alpha2: "KN", name: "Saint Kitts and Nevis"),
        Country(code: "LCA", alpha2: "LC", name: "Saint Lucia"),
        Country(code: "VCT", alpha2: "VC", name: "Saint Vincent and the Grenadines"),
        Country(code: "WSM", alpha2: "WS", name: "Samoa"),
        Country(code: "SMR", alpha2: "SM", name: "San Marino"),
        Country(code: "STP", alpha2: "ST", name: "São Tomé and Príncipe"),
        Country(code: "SAU", alpha2: "SA", name: "Saudi Arabia"),
        Country(code: "SEN", alpha2: "SN", name: "Senegal"),
        Country(code: "SRB", alpha2: "RS", name: "Serbia"),
        Country(code: "SYC", alpha2: "SC", name: "Seychelles"),
        Country(code: "SLE", alpha2: "SL", name: "Sierra Leone"),
        Country(code: "SGP", alpha2: "SG", name: "Singapore"),
        Country(code: "SVK", alpha2: "SK", name: "Slovakia"),
        Country(code: "SVN", alpha2: "SI", name: "Slovenia"),
        Country(code: "SLB", alpha2: "SB", name: "Solomon Islands"),
        Country(code: "SOM", alpha2: "SO", name: "Somalia"),
        Country(code: "ZAF", alpha2: "ZA", name: "South Africa"),
        Country(code: "SSD", alpha2: "SS", name: "South Sudan"),
        Country(code: "ESP", alpha2: "ES", name: "Spain"),
        Country(code: "LKA", alpha2: "LK", name: "Sri Lanka"),
        Country(code: "SDN", alpha2: "SD", name: "Sudan"),
        Country(code: "SUR", alpha2: "SR", name: "Suriname"),
        Country(code: "SWE", alpha2: "SE", name: "Sweden"),
        Country(code: "CHE", alpha2: "CH", name: "Switzerland"),
        Country(code: "SYR", alpha2: "SY", name: "Syria"),
        Country(code: "TWN", alpha2: "TW", name: "Taiwan"),
        Country(code: "TJK", alpha2: "TJ", name: "Tajikistan"),
        Country(code: "TZA", alpha2: "TZ", name: "Tanzania"),
        Country(code: "THA", alpha2: "TH", name: "Thailand"),
        Country(code: "TLS", alpha2: "TL", name: "Timor-Leste"),
        Country(code: "TGO", alpha2: "TG", name: "Togo"),
        Country(code: "TON", alpha2: "TO", name: "Tonga"),
        Country(code: "TTO", alpha2: "TT", name: "Trinidad and Tobago"),
        Country(code: "TUN", alpha2: "TN", name: "Tunisia"),
        Country(code: "TUR", alpha2: "TR", name: "Turkey"),
        Country(code: "TKM", alpha2: "TM", name: "Turkmenistan"),
        Country(code: "TUV", alpha2: "TV", name: "Tuvalu"),
        Country(code: "UGA", alpha2: "UG", name: "Uganda"),
        Country(code: "UKR", alpha2: "UA", name: "Ukraine"),
        Country(code: "ARE", alpha2: "AE", name: "United Arab Emirates"),
        Country(code: "GBR", alpha2: "GB", name: "United Kingdom"),
        Country(code: "USA", alpha2: "US", name: "United States"),
        Country(code: "URY", alpha2: "UY", name: "Uruguay"),
        Country(code: "UZB", alpha2: "UZ", name: "Uzbekistan"),
        Country(code: "VUT", alpha2: "VU", name: "Vanuatu"),
        Country(code: "VAT", alpha2: "VA", name: "Vatican City"),
        Country(code: "VEN", alpha2: "VE", name: "Venezuela"),
        Country(code: "VNM", alpha2: "VN", name: "Vietnam"),
        Country(code: "YEM", alpha2: "YE", name: "Yemen"),
        Country(code: "ZMB", alpha2: "ZM", name: "Zambia"),
        Country(code: "ZWE", alpha2: "ZW", name: "Zimbabwe"),
    ]
}
